version: "3.8"

services:
  #sqldjango:
    #image: mariadb
    #restart: always
    #environment:
      #MYSQL_ROOT_PASSWORD: example
      #MYSQL_DATABASE: example
      #MYSQL_USER: example
      #MYSQL_PASSWORD: example
    #volumes:
      #- sqlData:/var/lib/mysql
  appdjango:
    build:
      context: .
      dockerfile: djangodocker.dockerfile
    ports:
      - 80:80
    command: /usr/sbin/apache2ctl -D FOREGROUND
#volumes:
  #sqlData: